name: CI (build, lint, test)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (CMake, compiler, lint tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake build-essential \
            clang-format cppcheck

      - name: Configure (CMake)
        run: |
          mkdir -p build
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: |
          cmake --build build --config Release -- -j"$(nproc)"

      - name: Run tests (CTest)
        run: |
          cd build
          ctest --output-on-failure

      # --------- LINT ONLY NEW / CHANGED CODE IN PRs ---------

      - name: Static analysis (cppcheck on changed files)
        if: github.event_name == 'pull_request'
        run: |
          # Find changed C/C++ files between base branch and PR head
          git fetch origin ${{ github.base_ref }} --depth=1
          files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- \
            '*.c' '*.cc' '*.cpp' '*.cxx' '*.h' '*.hpp' '*.tpp')

          if [ -z "$files" ]; then
            echo "No C/C++ files changed, skipping cppcheck."
            exit 0
          fi

          echo "Running cppcheck on:"
          echo "$files"

          cppcheck \
            --enable=all \
            --error-exitcode=1 \
            --std=c++20 \
            --inline-suppr \
            --quiet \
            --suppress=missingIncludeSystem \
            --suppress=*:*build/* \
            $files

      - name: clang-format (style check on changed files)
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- \
            '*.h' '*.hpp' '*.c' '*.cc' '*.cpp' '*.cxx' '*.tpp')

          if [ -z "$files" ]; then
            echo "No C/C++ files changed, skipping clang-format."
            exit 0
          fi

          clang-format --version
          echo "$files" | xargs -I{} clang-format --dry-run -Werror "{}"
